# 端口、数据源、thymeleaf、mybatis、表单转换
server:
  port: 9981

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/plc?serverTimezone=GMT%2B8

  mail:
      host: smtp.qq.com
      username: 2138155993@qq.com
      password: diyjfawjyickeaca
      properties.mail.smtp.auth: true
      properties.mail.smtp.starttls.enable: true
      default-encoding: utf-8


  thymeleaf:
    cache: false
    mode: HTML5

  mvc:
    hiddenmethod:
      filter:
        enabled: true
    throw-exception-if-no-handler-found: true

  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: cn.qqcn.entity
  configuration:
    map-underscore-to-camel-case: true  # 驼峰转换

logging:
  level:
    cn.qqcn: debug
